### ISSUE TITLE
The close event from modal on ESC key press is sent to UserLive.Show module

### ISSUE THREAD

**Issue by mindreframer** [jprincipe/surface_demo#1]
```
[error] GenServer #PID<0.610.0> terminating
** (UndefinedFunctionError) function SurfaceDemoWeb.UserLive.Show.handle_event/3 is undefined or private
    (surface_demo 0.1.0) SurfaceDemoWeb.UserLive.Show.handle_event("close", %{"key" => "Escape"}, #Phoenix.LiveView.Socket<assigns: %{__context__: %{}, __surface__: %{}, flash: %{}, live_action: :edit, page_title: "Edit User", user: %SurfaceDemo.Accounts.User{__meta__: #Ecto.Schema.Metadata<:loaded, "users">, ...}}, changed: %{}, endpoint: SurfaceDemoWeb.Endpoint, id: "phx-FkyUPiiJbnhlvQNB", parent_pid: nil, root_pid: #PID<0.610.0>, router: SurfaceDemoWeb.Router, view: SurfaceDemoWeb.UserLive.Show, ...>)
    (phoenix_live_view 0.15.0) lib/phoenix_live_view/channel.ex:338: anonymous fn/3 in Phoenix.LiveView.Channel.view_handle_event/3
    (telemetry 0.4.2) /Users/roman/Desktop/elixir-lv/surface_demo/deps/telemetry/src/telemetry.erl:262: :telemetry.span/3
    (phoenix_live_view 0.15.0) lib/phoenix_live_view/channel.ex:203: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 3.13) gen_server.erl:680: :gen_server.try_dispatch/4
    (stdlib 3.13) gen_server.erl:756: :gen_server.handle_msg/6
    (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Message{event: "event", join_ref: "9", payload: %{"event" => "close", "type" => "keydown", "value" => %{"key" => "Escape"}}, ref: "23", topic: "lv:phx-FkyUPiiJbnhlvQNB"}
```

The handler in the modal component is not triggered...

```
  @impl true
  def handle_event("close", _, socket) do
    {:noreply, push_patch(socket, to: socket.assigns.return_to)}
  end
```

**Comment by jprincipe** [comment]
Nice catch @mindreframer.  I have updated the `modal_component.ex` to use the Surface `:on-[event]` directives so it can take advantage of the auto `phx-target` assignment.  That seems to have done the trick

**Comment by mindreframer** [comment]
Thanks for the quick fix and have a great day!
